version: 2

jobs:
  lint:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run: hadolint Dockerfile
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: make build
      - run: docker save renatomefi/docker-testinfra -o ./tmp/renatomefi-docker-testinfra.tar
      - persist_to_workspace:
          root: ./tmp
          paths:
            - renatomefi-docker-testinfra.tar
            - tags.list
  test:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - run: docker load -i ./tmp/renatomefi-docker-testinfra.tar
      - run: make test
  scan-vulnerability:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: ./tmp
      - run:
          name: Update Docker Compose
          command: |
            sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Install clair-scanner
          command: |
            sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 -o /usr/local/bin/clair-scanner
            sudo chmod +x /usr/local/bin/clair-scanner
      - run: docker load -i ./tmp/renatomefi-docker-testinfra.tar
      - run: make ci-scan-vulnerability
      - store_artifacts:
          path: ./tmp/clair

workflows:
  version: 2
  lint_build_test_scan:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - scan-vulnerability:
          requires:
            - build
